version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install

  lint:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Linting
          command: yarn lint

  unit_tests:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: yarn test:unit

  integration_tests:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Integration Tests
          command: yarn test:integration

  clean_up:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Clean up
          command: yarn clean

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - lint
      - integration_tests:
          requires:
            - unit_tests
      - clean_up:
          requires:
            - integration_tests
