version: 2.1

jobs:
  build:
    docker:
      - image: node:latest

    working_directory: /usr/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: yarn install

      # Run linting
      - run:
          name: Linting
          command: yarn lint

      # Run unit tests
      - run:
          name: Unit Tests
          command: yarn test:unit

      # Run integration tests
      - run:
          name: Integration Tests
          command: yarn test:integration

      # Clean up
      - run:
          name: Clean up
          command: yarn clean

      # Store test artifacts
      - store_artifacts:
          path: test-results.xml

      # Save test result
      - store_test_results:
          path: test-results.xml

