version: 2.1

jobs:
  build:
    docker:
      - image: node # Use the official Node.js image
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build TypeScript code
          command: yarn build
      - run:
          name: Run tests
          command: yarn test:unit && yarn test:integration
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_to_prod:
    docker:
      - image: node # Use the same Node.js image
    working_directory: /usr/app
    steps:
      - attach_workspace:
          at: /usr/app
      - run:
          name: Deploy application to production
          command: |
            if [ "${CIRCLE_JOB}" == "build" ]; then
              git config --global user.email "marcin.mysliw@gmail.com"
              git config --global user.name "Marcin Mysliwiec"
              git clone https://github.com/MarcinMysliwiec/marcin-mysliwiec-path-1-prod.git
              cp -r ./* marcin-mysliwiec-path-1-prod/
              cd marcin-mysliwiec-path-1-prod
              git add .
              git commit -m "CircleCI deployment"
              git push origin master
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_prod:
          requires:
            - build
          filters:
            branches:
              only: master
