version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install

  lint:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - attach_workspace:
          at: /usr/app
      - run:
          name: Linting
          command: yarn lint

  unit_tests:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - attach_workspace:
          at: /usr/app
      - run:
          name: Unit Tests
          command: yarn test:unit

  integration_tests:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - attach_workspace:
          at: /usr/app
      - run:
          name: Integration Tests
          command: yarn test:integration

  clean_up:
    docker:
      - image: node:latest
    working_directory: /usr/app
    steps:
      - attach_workspace:
          at: /usr/app
      - run:
          name: Clean up
          command: yarn clean

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
            - lint
      - integration_tests:
          requires:
            - install_dependencies
            - unit_tests
      - clean_up:
          requires:
            - install_dependencies
            - integration_tests

# Deploy job to test environment 
# jobs:
#   deploy:
#     machine:
#       enabled: true
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "${SSH_KEY_FINGERPRINT}"
#       - run:
#           name: Push to GitHub
#           command: |
#             git config --global user.email "${GIT_EMAIL}"
#             git config --global user.name "${GIT_NAME}"
#             git clone "${REPO_URL}"
#             cd "${PROJECT_NAME}"
#             cp -r /usr/app/* .
#             git add .
#             git commit -m "Automated deployment"
#             git push origin main