version: 2.1

jobs:
  build:
    docker:
      - image: node
    working_directory: /usr/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build TypeScript code
          command: yarn build
      - run:
          name: Run tests
          command: yarn test:unit && yarn test:integration
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: node
    working_directory: /usr/app
    steps:
      - attach_workspace:
          at: /usr/app
      - run:
          name: Deploy application
          command: |
            yarn install --production
            yarn start

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
