name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn install
        working-directory: /usr/app

      - name: Build TypeScript code
        run: yarn build
        working-directory: /usr/app

      - name: Run tests
        run: yarn test:unit && yarn test:integration
        working-directory: /usr/app